name: only_test

on:
  push:
  workflow_dispatch:

jobs:

  cocotbtest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@tt07
